[album_total]
title = "벅스 ─ 최신 음악 ─ 앨범 ─ 전체"
url = "https://music.bugs.co.kr/newest/album/total"
entrySelector = "ul.list.tileView.albumList li"
titleSelector = "figcaption.info div.albumTitle a"
linkSelector = "figcaption.info div.albumTitle a"
contentSelector = "div.subInfo"
imageSelector = "div.thumbnail a img"
waitUntil = "networkidle"